### ISSUE TITLE
Documentation: also need freeglut3 to compile on linux

### ISSUE THREAD

**Issue by dom11990** [thomaslepoix/Qucs-RFlayout#13]
Title says it all...

**Comment by thomaslepoix** [comment]
Which distro / version do you use?

It seems strange to me, because on [travis (Ubuntu Bionic)](https://github.com/thomaslepoix/Qucs-RFlayout/blob/master/.travis.yml) and [docker (Debian Buster-slim)](https://github.com/thomaslepoix/Qucs-RFlayout/blob/master/pack/Dockerfile.unix), `qt5-default` with its dependencies and recommended packages (`libqt5opengl5-dev`) is enough to build.

**Comment by dom11990** [comment]
I'm on Debian 10

**Comment by thomaslepoix** [comment]
What was the error message?

**Comment by thomaslepoix** [comment]
I just installed the `.deb` package on a fresh Ubuntu 20.04 and everything works well without `freeglut3`. About OpenGL, `libqt5opengl5` is enough at runtime and thus `libqt5opengl5-dev` at build time.

**Comment by dom11990** [comment]
I'm running on the latest debian 10 (buster) and a new VM I just set up needed to install lglut to compile. Regardless of if a standard distro like Ubuntu comes with the package or not, I think it makes sense to include it in the dependencies list.
